27 implement weighted grade in course evaluation
ApplETS/ETS-API-Clients pull request #28
Opened 2024-04-11 19:19 UTC by DylanApardian

## Closes
#27 

## Description

This PR implements `weightedGrade` as part of `CourseEvaluation`. This way, we don't need to calculate it in Notre-Dame, more specifically in https://github.com/ApplETS/Notre-Dame/pull/921

## Testing
I modified 2 tests to also check the `weightedGrade`. 
I hard-coded the expected values. It's not my preferred way but there are already a lot of hard-coded values and if they don't change, I suppose it's alright.

2024-04-11 19:21 UTC, XavierPaquet-Rapold requested changes

2024-04-11 19:21 UTC, XavierPaquet-Rapold commented on lib/src/models/course_evaluation.dart
> +    return double.parse(result.toStringAsFixed(2));
Serait-il mieux de faire que ça retourne un nullable ? Comme ça si le mark est null, on peut écrire N/A

2024-04-11 19:47 UTC, DylanApardian commented on lib/src/models/course_evaluation.dart
> +    return double.parse(result.toStringAsFixed(2));
done

2024-04-11 20:29 UTC, XavierPaquet-Rapold commented on lib/src/models/course_evaluation.dart
> +  }
```suggestion
  double? get weightedGrade =>
    mark == null ||
     correctedEvaluationOutOfFormatted == 0.0 ||
     weight == 0.0
        ? null
        : (mark! / correctedEvaluationOutOfFormatted) * weight;
  }
```

2024-04-12 00:00 UTC, DylanApardian commented on lib/src/models/course_evaluation.dart
> +  }
done

2024-04-12 00:10 UTC, XavierPaquet-Rapold approved these changes
LGTM 🔥

2024-04-12 00:15 UTC, merged